### ISSUE TITLE
摩托车商业保险

### ISSUE THREAD

**Issue by EarthChen** [EngrZhou/moyou#14]
想请问一下北京摩托车商业保险的相关问题和购买途径，看官网写仅360、奇安信加入，故此 issue 询问

**Comment by AzureFatty** [comment]
摩托车商业险购买环境越来越恶劣了，附加条件很多，费用也越来越贵了。

比如：三者现在起步价已经1000元左右了。
之前谈的有渠道，仅仅也是在公布价格基础上便宜百十元。

关于加入，主要是因为群内的氛围还算比较友好，为了维护群内的这种环境，我们更倾向于可以见面的社交。

中间我们也尝试过允许通过这个渠道的摩友进群，但是发现这批摩友因为跟我们无法现实中见面，且活跃度很低往往处于潜水状态，因此这个入群条件继续收缩了。@EarthChen 很抱歉。
